### PR TITLE
Terri

### PR DESCRIPTION
**Pull request by tjaskolka**
ready to merge

### CODE REVIEW

**Review by jacobi973 — CHANGES_REQUESTED** [review]
The swagger JSON file in of itself looks great. However, the problem with editing the JSON file is that whenever we need to run the command to generate new documentation, all your work will be gone due to auto-generation of content. 

The best way to create good swagger documentation is by looking at this page [Swagger Autogen](https://www.npmjs.com/package/swagger-autogen).  A bit downwards into the page you will find examples on how to create stuff that will last with each new documentation. ie   
at the recipe routes index for creating a new recipe it needs to look something like this. 
routes.post('/', validation.addNewRecipe,
        /*  #swagger.parameters['obj'] = {
                in: 'body',
                description: 'Some description...',
                schema: {
                    $name: 'Pizza Pie', ($ means it will be a required field)
                    $ingredients: ['pizza', 'pasta', 'salad'],
                    imageLink: 'Pizza.jpg'
                }
        } */
         recipes.create);
         
Another thing to look at is the swagger.js file. This is where you will be able to specify schemes, the host, info about our api.
Here is what I did previously that can be an example and that will keep each time we run the command. 
const swaggerAutogen = require('swagger-autogen')();

const doc = {
  info: {
    title: 'My API',
    description: '',
  },
  host: ,
  basePath: '/',
  schemes: ['https','http'],
};

const outputFile = './swagger.json';
const endpointsFiles = ['./routes/index.js'];

swaggerAutogen(outputFile, endpointsFiles, doc);

**Comment by tjaskolka** [comment]
Thanks, Jacob. I realize the changes would be lost, but I have been backing them up on my end. The documentation was part of what I was studying when you asked me to make it happen (sorry, I know you asked Wednesday, but I didn't see the request until Friday). I hadn't gotten to the point of getting the documentation within the appropriate files to work so I edited the swagger.json file for this week's activity. I was excited to see I could actually provide a dropdown for choosing options that needed to be restricted (such as valid users), so I hope that will prove useful. 

I will continue to work on the documentation and getting it where it needs to go permanently, as well as forming the graphql queries. I see that they should be taking the place of REST, so that's what I'm going for, especially in regards to querying more than one collection. :)

**Comment by tjaskolka** [comment]
I am not understanding what changes you are requesting from me. (
***@***.**** requested changes on this pull request. )

I am sorry to be troublesome with this. Github with a group is one of my
weak spots (all the stuff I was stronger in got spoken for, but that's ok,
I need to learn). Documentation was another weak spot. I did not have time
to figure out how to go beyond documenting manually on the last project, so
it is taking a little while for me to catch up with that, sorry.

**Comment by jacobi973** [comment]
Don't worry about finishing up the documentation this week. I would however like the permanent swagger documentation and not temporary solution in the master files. The changes I was suggesting were getting it to become permanent.  Here is a quick example I just did inside the recipe-routes.js file. 
image

**Review by jacobi973 — APPROVED** [review]

**Comment by tjaskolka** [comment]
Oh, that was the plan all along. I was just trying to satisfy this week's
assignment.

**Pull request merged**
